import { commands, enrouteTask } from "../actions";
import type { TActionType, TUpperLevelTasks } from "../../types";

type TAutoActions = Record<
  string,
  Record<
    TUpperLevelTasks,
    Array<{
      actionType: TActionType;
      data: any;
    }>
  >
>;

export const autoActions: TAutoActions = {
  all: {
    Default: [{ actionType: "commands", data: commands.ELPRS }],
    AWACS: [{ actionType: "enrouteTask", data: enrouteTask.AWACS }],
    Refueling: [
      { actionType: "enrouteTask", data: enrouteTask.Tanker },
      { actionType: "commands", data: commands.ActivateBeacon },
    ],
    "Fighter Sweep": [{ actionType: "enrouteTask", data: enrouteTask.FighterSweep }],
    CAS: [{ actionType: "enrouteTask", data: enrouteTask.CAS }],
    CAP: [{ actionType: "enrouteTask", data: enrouteTask.CAP }],
    SEAD: [
      { actionType: "enrouteTask", data: enrouteTask.SEAD },
      {
        actionType: "options",
        data: {
          name: 1,
          value: 4,
        },
      },
    ],
    "Antiship Strike": [{ actionType: "enrouteTask", data: enrouteTask.AntiShip }],
    AFAC: [{ actionType: "enrouteTask", data: enrouteTask.FAC }],
    Escort: [],
    Reconnaissance: [],
    "Runway Attack": [],
    GAI: [],
    "Ground Attack": [],
    Nothing: [],
    Transport: [],
    Airborne: [],
    Intercept: [],
    "Pinpoint Strike": [],
  },
  plane: {
    Default: [],
    AWACS: [],
    Refueling: [],
    "Fighter Sweep": [
      {
        actionType: "options",
        data: { name: 17, value: true },
      },
      {
        actionType: "options",
        data: { name: 18, value: 4 },
      },
      {
        actionType: "options",
        data: { name: 19, value: true },
      },
      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    CAS: [
      {
        actionType: "options",
        data: { name: 1, value: 2 },
      },
      {
        actionType: "options",
        data: { name: 3, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 5, value: 131074, variantIndex: 2, formationIndex: 2 },
      },
      {
        actionType: "options",
        data: { name: 15, value: true },
      },
      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
      {
        actionType: "options",
        data: { name: 19, value: true },
      },
    ],
    CAP: [
      {
        actionType: "options",
        data: { name: 17, value: true },
      },
      {
        actionType: "options",
        data: { name: 18, value: 4 },
      },
      {
        actionType: "options",
        data: {
          name: 19,
          value: true,
        },
      },

      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    SEAD: [
      {
        actionType: "options",
        data: { name: 13, value: 2 },
      },

      {
        actionType: "options",
        data: {
          name: 19,
          value: true,
        },
      },
      {
        actionType: "options",
        data: {
          name: 21,
          value: "Air Defence;",
          targetTypes: ["Air Defence"],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    "Antiship Strike": [
      {
        actionType: "options",
        data: { name: 1, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 3, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 5, value: 131074, variantIndex: 2, formationIndex: 2 },
      },

      {
        actionType: "options",
        data: { name: 15, value: true },
      },
      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    AFAC: [],
    Escort: [
      {
        actionType: "options",
        data: { name: 17, value: true },
      },
      {
        actionType: "options",
        data: { name: 18, value: 4 },
      },
      {
        actionType: "options",
        data: {
          name: 19,
          value: true,
        },
      },

      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    Intercept: [
      {
        actionType: "options",
        data: { name: 17, value: true },
      },
      {
        actionType: "options",
        data: { name: 18, value: 4 },
      },
      {
        actionType: "options",
        data: {
          name: 19,
          value: true,
        },
      },

      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    "Ground Attack": [
      {
        actionType: "options",
        data: { name: 1, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 3, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 5, value: 131074, variantIndex: 2, formationIndex: 2 },
      },

      {
        actionType: "options",
        data: { name: 15, value: true },
      },
      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    "Pinpoint Strike": [
      {
        actionType: "options",
        data: { name: 1, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 3, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 5, value: 131074, variantIndex: 2, formationIndex: 2 },
      },

      {
        actionType: "options",
        data: { name: 15, value: true },
      },
      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    "Runway Attack": [
      {
        actionType: "options",
        data: { name: 1, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 3, value: 1 },
      },
      {
        actionType: "options",
        data: { name: 5, value: 131074, variantIndex: 2, formationIndex: 2 },
      },

      {
        actionType: "options",
        data: { name: 15, value: true },
      },
      {
        actionType: "options",
        data: {
          name: 21,
          value: "none;",
          targetTypes: [],
          noTargetTypes: [
            "Fighters",
            "Multirole fighters",
            "Bombers",
            "Helicopters",
            "UAVs",
            "Infantry",
            "Fortifications",
            "Tanks",
            "IFV",
            "APC",
            "Artillery",
            "Unarmed vehicles",
            "AAA",
            "SR SAM",
            "MR SAM",
            "LR SAM",
            "Aircraft Carriers",
            "Cruisers",
            "Destroyers",
            "Frigates",
            "Corvettes",
            "Light armed ships",
            "Unarmed ships",
            "Submarines",
            "Cruise missiles",
            "Antiship Missiles",
            "AA Missiles",
            "AG Missiles",
            "SA Missiles",
          ],
        },
      },
    ],
    Nothing: [],
    Reconnaissance: [],
    Transport: [],
    Airborne: [],
    GAI: [],
  },
  vehicle: {
    Default: [
      { actionType: "commands", data: commands.ELPRS },
      { actionType: "enrouteTask", data: enrouteTask.EWR },
    ],
    AFAC: [],
    AWACS: [],
    Refueling: [],
    "Fighter Sweep": [],
    CAS: [],
    CAP: [],
    SEAD: [],
    "Antiship Strike": [],
    Escort: [],
    Intercept: [],
    "Ground Attack": [],
    "Pinpoint Strike": [],
    "Runway Attack": [],
    Nothing: [],
    Reconnaissance: [],
    Transport: [],
    Airborne: [],
    GAI: [],
  },
  ship: {
    Default: [{ actionType: "commands", data: commands.ActivateBeacon }],
    AFAC: [],
    AWACS: [],
    Refueling: [],
    "Fighter Sweep": [],
    CAS: [],
    CAP: [],
    SEAD: [],
    "Antiship Strike": [],
    Escort: [],
    Intercept: [],
    "Ground Attack": [],
    "Pinpoint Strike": [],
    "Runway Attack": [],
    Nothing: [],
    Reconnaissance: [],
    Transport: [],
    Airborne: [],
    GAI: [],
  },
};
