export enum PerformCommand {
  noAction = "NoAction",
  runScript = "Script",
  scriptFile = "ScriptFile",
  setCallsign = "SetCallsign",
  setFrequency = "SetFrequency",
  setFrequencyForUnit = "SetFrequencyForUnit",
  transmitMessage = "TransmitMessage",
  stopTransmitting = "StopTransmission",
  switchWaypoint = "SwitchWaypoint",
  switchAction = "SwitchAction",
  setInvisible = "SetInvisible",
  setImmortal = "SetImmortal",
  start = "Start",
  loadingShip = "LoadingShip",
  activateBeacon = "ActivateBeacon",
  deactivateBeacon = "DeactivateBeacon",
  activateICLS = "ActivateICLS",
  deactivateICLS = "DeactivateICLS",
  activateLink4 = "ActivateLink4",
  deactivateLink4 = "DeactivateLink4",
  activateACLS = "ActivateACLS",
  deactivateACLS = "DeactivateACLS",
  elprs = "ELPRS",
  smokeOnOff = "SMOKE_ON_OFF",
}
