export enum PerformCommand {
  noAction = "NoAction",
  runScript = "Script",
  scriptFile = "ScriptFile",
  setCallsign = "SetCallsign",
  setFrequency = "SetFrequency",
  setFrequencyForUnit = "SetFrequencyForUnit",
  transmitMessage = "TransmitMessage",
  stopTransmitting = "StopTransmission",
  switchWaypoint = "SwitchWaypoint",
  switchAction = "SwitchAction",
  setInvisible = "SetInvisible",
  setImmortal = "SetImmortal",
  start = "Start",
  loadingShip = "LoadingShip",
  activateBeacon = "ActivateBeacon",
  deactivateBeacon = "DeactivateBeacon",
  activateICLS = "ActivateICLS",
  deactivateICLS = "DeactivateICLS",
  activateLink4 = "ActivateLink4",
  deactivateLink4 = "DeactivateLink4",
  activateACLS = "ActivateACLS",
  deactivateACLS = "DeactivateACLS",
  elprs = "ELPRS",
  smokeOnOff = "SMOKE_ON_OFF",
}

export enum OptionName {
  noOption = -1,
  roe = 0,
  reactionOnThreat = 1,
  radarUsing = 3,
  flareUsing = 4,
  formation = 5,
  rtbOnBingo = 6,
  silence = 7,
  disperseOnAttack = 8,
  alarmState = 9,
  rtbOnOutOfAmmo = 10,
  awarnessLevel = 11,
  following = 12,
  ecmUsing = 13,
  prohibitAA = 14,
  prohibitJett = 15,
  prohibitAB = 16,
  prohibitAG = 17,
  missileAttack = 18,
  prohibitWpPassReport = 19,
  engageAirWeapons = 20,
  radioUsageContact = 21,
  radioUsageEngage = 22,
  radioUsageKill = 23,
  aircraftInterceptRange = 24,
  jettTanksIfEmpty = 25,
  forcedAttack = 26,
  altRestrictionMin = 27,
  restrictTarget = 28,
  altRestrictionMax = 29,
}

export enum Formation {
  line_abreast = 1,
  trail = 2,
  wedge = 3,
  echelon_right = 4,
  echelon_left = 5,
  finger_four = 6,
  spread_four = 7,
  heli_wedge = 8,
  heli_echelon = 9,
  heli_front = 10,
  heli_column = 11,
  ww2_bomber_element = 12,
  ww2_bomber_element_height = 13,
  ww2_fighter_vic = 14,
  modern_bomber_element = 17,
}

export enum Task {
  noTask = "NoTask",
  attackGroup = "AttackGroup",
  attackUnit = "AttackUnit",
  attackMapObject = "AttackMapObject",
  bombing = "Bombing",
  bombingRunway = "BombingRunway",
  orbit = "Orbit",
  land = "Land",
  refueling = "Refueling",
  facAttackGroup = "FAC_AttackGroup",
  fireAtPoint = "FireAtPoint",
  hold = "Hold",
  follow = "Follow",
  escort = "Escort",
  embarkToTransport = "EmbarkToTransport",
  goToWaypoint = "GoToWaypoint",
  embarking = "Embarking",
  disembarking = "Disembarking",
  attachTrailer = "AttachTrailer",
  detachTrailer = "DetachTrailer",
  cargoTransportation = "CargoTransportation",
  cargoTransportationPlane = "CargoTransportationPlane",
  cargoUnloadPlane = "CargoUnloadPlane",
  aerobatics = "Aerobatics",
  carpetBombing = "CarpetBombing",
  followBigFormation = "FollowBigFormation",
  groundEscort = "GroundEscort",
  paratroopersDrop = "ParatroopersDrop",
}

export enum EnrouteTask {
  noTask = "NoTask",
  engageTargets = "EngageTargets",
  engageTargetsInZone = "EngageTargetsInZone",
  engageGroup = "EngageGroup",
  engageUnit = "EngageUnit",
  awacs = "AWACS",
  ewr = "EWR",
  tanker = "Tanker",
  fac = "FAC",
  facEngageGroup = "FAC_EngageGroup",
  shipHoldPoint = "ShipHoldPoint",
  recoveryTanker = "RecoveryTanker",
}

export enum EngageTargets {
  fighterSweep = "FighterSweep",
  cas = "CAS",
  cap = "CAP",
  sead = "SEAD",
  antiShip = "AntiShip",
}
