import {
  EnrouteTask,
  type TEnrouteTask,
  OptionName,
  type TOptionName,
  PerformCommand,
  type TPerformCommand,
  Task,
  type TPerformTask,
} from "./consts";
import type { TConstsList, TUpperLevelTasks } from "../types";
import { performTask, enrouteTask, commands, options } from "./actions";

type AvailableActions = Record<
  "plane" | "helicopter" | "vehicle" | "ship",
  Record<
    "task" | "enrouteTask" | "commands" | "options",
    Record<
      TUpperLevelTasks,
      Array<TConstsList<TPerformTask | TEnrouteTask | TPerformCommand | TOptionName>>
    >
  >
>;

export const availableActions: AvailableActions = {
  plane: {
    task: {
      Default: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.attackMapObject],
        performTask[Task.bombing],
        performTask[Task.bombingRunway],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.facAttackGroup],
        performTask[Task.follow],
        performTask[Task.aerobatics],
        performTask[Task.followBigFormation],
        performTask[Task.cargoTransportationPlane],
        performTask[Task.cargoUnloadPlane],
      ],
      Nothing: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.aerobatics],
      ],
      Airborne: [
        performTask[Task.noTask],
        performTask[Task.paratroopersDrop],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.followBigFormation],
      ],
      SEAD: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.escort],
      ],
      "Antiship Strike": [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
      ],
      AWACS: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
      ],
      CAS: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.aerobatics],
      ],
      CAP: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.aerobatics],
      ],
      "Pinpoint Strike": [
        performTask[Task.noTask],
        performTask[Task.attackMapObject],
        performTask[Task.bombing],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
      ],
      Escort: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.escort],
      ],
      "Fighter Sweep": [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.aerobatics],
      ],
      GAI: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
      ],
      "Ground Attack": [
        performTask[Task.noTask],
        performTask[Task.attackMapObject],
        performTask[Task.bombing],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.aerobatics],
        performTask[Task.carpetBombing],
        performTask[Task.followBigFormation],
      ],
      Intercept: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.aerobatics],
      ],
      AFAC: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.facAttackGroup],
        performTask[Task.bombing],
        performTask[Task.attackMapObject],
        performTask[Task.follow],
      ],
      Reconnaissance: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.aerobatics],
      ],
      Refueling: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.recoveryTanker],
      ],
      "Runway Attack": [
        performTask[Task.noTask],
        performTask[Task.attackMapObject],
        performTask[Task.bombing],
        performTask[Task.bombingRunway],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
      ],
      Transport: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.refueling],
        performTask[Task.follow],
        performTask[Task.aerobatics],
        performTask[Task.followBigFormation],
        performTask[Task.cargoTransportationPlane],
        performTask[Task.cargoUnloadPlane],
      ],
    },
    enrouteTask: {
      Default: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.awacs],
        enrouteTask[EnrouteTask.fac],
        enrouteTask[EnrouteTask.facEngageGroup],
        enrouteTask[EnrouteTask.tanker],
      ],
      Nothing: [enrouteTask[EnrouteTask.noEnrouteTask]],
      SEAD: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.sead],
      ],
      "Antiship Strike": [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.antiShip],
      ],
      AWACS: [enrouteTask[EnrouteTask.noEnrouteTask], enrouteTask[EnrouteTask.awacs]],
      CAS: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.cas],
      ],
      "Pinpoint Strike": [enrouteTask[EnrouteTask.noEnrouteTask]],
      CAP: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.cap],
      ],
      Escort: [enrouteTask[EnrouteTask.noEnrouteTask]],
      "Fighter Sweep": [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.fighterSweep],
      ],
      GAI: [enrouteTask[EnrouteTask.noEnrouteTask]],
      "Ground Attack": [enrouteTask[EnrouteTask.noEnrouteTask]],
      Intercept: [enrouteTask[EnrouteTask.noEnrouteTask]],
      AFAC: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.fac],
        enrouteTask[EnrouteTask.facEngageGroup],
      ],
      Reconnaissance: [enrouteTask[EnrouteTask.noEnrouteTask]],
      Refueling: [enrouteTask[EnrouteTask.noEnrouteTask], enrouteTask[EnrouteTask.tanker]],
      "Runway Attack": [enrouteTask[EnrouteTask.noEnrouteTask]],
      Transport: [enrouteTask[EnrouteTask.noEnrouteTask]],
      Airborne: [],
    },
    commands: {
      Default: [
        commands[PerformCommand.noAction],
        commands[PerformCommand.runScript],
        commands[PerformCommand.scriptFile],
        commands[PerformCommand.setFrequency],
        commands[PerformCommand.setFrequencyForUnit],
        commands[PerformCommand.transmitMessage],
        commands[PerformCommand.stopTransmitting],
        commands[PerformCommand.switchWaypoint],
        commands[PerformCommand.switchAction],
        commands[PerformCommand.setInvisible],
        commands[PerformCommand.setImmortal],
        commands[PerformCommand.start],
        commands[PerformCommand.activateBeacon],
        commands[PerformCommand.deactivateBeacon],
        commands[PerformCommand.elprs],
        commands[PerformCommand.smokeOnOff],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    options: {
      Default: [
        options[OptionName.noOption],
        options[OptionName.roe],
        options[OptionName.reactionOnThreat],
        options[OptionName.radarUsing],
        options[OptionName.flareUsing],
        options[OptionName.formation],
        options[OptionName.rtbOnBingo],
        options[OptionName.rtbOnOutOfAmmo],
        options[OptionName.silence],
        options[OptionName.awarnessLevel],
        options[OptionName.ecmUsing],
        options[OptionName.prohibitAA],
        options[OptionName.prohibitJett],
        options[OptionName.prohibitAB],
        options[OptionName.prohibitAG],
        options[OptionName.missileAttack],
        options[OptionName.prohibitWpPassReport],
        options[OptionName.radioUsageContact],
        options[OptionName.radioUsageEngage],
        options[OptionName.radioUsageKill],
        options[OptionName.jettTanksIfEmpty],
        options[OptionName.forcedAttack],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
  },
  helicopter: {
    task: {
      Default: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.attackMapObject],
        performTask[Task.bombing],
        performTask[Task.bombingRunway],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.facAttackGroup],
        performTask[Task.follow],
        performTask[Task.cargoTransportation],
        performTask[Task.groundEscort],
      ],
      Nothing: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.follow],
      ],
      SEAD: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.follow],
        performTask[Task.escort],
        performTask[Task.cargoTransportation],
        performTask[Task.groundEscort],
      ],
      "Antiship Strike": [
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.follow],
        performTask[Task.cargoTransportation],
      ],
      CAS: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.follow],
        performTask[Task.embarking],
        performTask[Task.disembarking],
        performTask[Task.cargoTransportation],
        performTask[Task.groundEscort],
      ],
      "Ground Attack": [
        performTask[Task.noTask],
        performTask[Task.attackMapObject],
        performTask[Task.bombing],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.follow],
        performTask[Task.embarking],
        performTask[Task.disembarking],
        performTask[Task.groundEscort],
      ],
      AFAC: [
        performTask[Task.noTask],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.facAttackGroup],
        performTask[Task.bombing],
        performTask[Task.attackMapObject],
        performTask[Task.follow],
      ],
      Reconnaissance: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.follow],
      ],
      Transport: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.follow],
        performTask[Task.embarking],
        performTask[Task.disembarking],
        performTask[Task.cargoTransportation],
      ],
      Escort: [
        performTask[Task.noTask],
        performTask[Task.orbit],
        performTask[Task.land],
        performTask[Task.escort],
      ],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    enrouteTask: {
      Default: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.fac],
        enrouteTask[EnrouteTask.facEngageGroup],
      ],
      Nothing: [enrouteTask[EnrouteTask.noEnrouteTask]],
      SEAD: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.sead],
      ],
      "Antiship Strike": [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.antiShip],
      ],
      CAS: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.cas],
      ],
      "Ground Attack": [enrouteTask[EnrouteTask.noEnrouteTask]],
      AFAC: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.engageTargets],
        enrouteTask[EnrouteTask.engageTargetsInZone],
        enrouteTask[EnrouteTask.engageGroup],
        enrouteTask[EnrouteTask.engageUnit],
        enrouteTask[EnrouteTask.fac],
        enrouteTask[EnrouteTask.facEngageGroup],
      ],
      Reconnaissance: [enrouteTask[EnrouteTask.noEnrouteTask]],
      Escort: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    commands: {
      Default: [
        commands[PerformCommand.noAction],
        commands[PerformCommand.runScript],
        commands[PerformCommand.scriptFile],
        commands[PerformCommand.setFrequency],
        commands[PerformCommand.setFrequencyForUnit],
        commands[PerformCommand.transmitMessage],
        commands[PerformCommand.stopTransmitting],
        commands[PerformCommand.switchWaypoint],
        commands[PerformCommand.switchAction],
        commands[PerformCommand.setInvisible],
        commands[PerformCommand.setImmortal],
        commands[PerformCommand.start],
        commands[PerformCommand.activateBeacon],
        commands[PerformCommand.deactivateBeacon],
        commands[PerformCommand.elprs],
        commands[PerformCommand.smokeOnOff],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    options: {
      Default: [
        options[OptionName.noOption],
        options[OptionName.roe],
        options[OptionName.reactionOnThreat],
        options[OptionName.radarUsing],
        options[OptionName.flareUsing],
        options[OptionName.formation],
        options[OptionName.rtbOnBingo],
        options[OptionName.rtbOnOutOfAmmo],
        options[OptionName.silence],
        options[OptionName.awarnessLevel],
        options[OptionName.jettTanksIfEmpty],
        options[OptionName.prohibitWpPassReport],
        options[OptionName.radioUsageContact],
        options[OptionName.radioUsageEngage],
        options[OptionName.radioUsageKill],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
  },
  vehicle: {
    task: {
      Default: [
        performTask[Task.noTask],
        performTask[Task.facAttackGroup],
        performTask[Task.fireAtPoint],
        performTask[Task.attackGroup],
        performTask[Task.attackUnit],
        performTask[Task.hold],
        performTask[Task.embarkToTransport],
        performTask[Task.goToWaypoint],
        performTask[Task.embarking],
        performTask[Task.disembarking],
        performTask[Task.attachTrailer],
        performTask[Task.detachTrailer],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    enrouteTask: {
      Default: [
        enrouteTask[EnrouteTask.noEnrouteTask],
        enrouteTask[EnrouteTask.fac],
        enrouteTask[EnrouteTask.facEngageGroup],
        enrouteTask[EnrouteTask.ewr],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    commands: {
      Default: [
        commands[PerformCommand.noAction],
        commands[PerformCommand.runScript],
        commands[PerformCommand.scriptFile],
        commands[PerformCommand.setCallsign],
        commands[PerformCommand.setFrequency],
        commands[PerformCommand.transmitMessage],
        commands[PerformCommand.stopTransmitting],
        commands[Task.goToWaypoint],
        commands[PerformCommand.setInvisible],
        commands[PerformCommand.setImmortal],
        commands[PerformCommand.elprs],
        commands[PerformCommand.activateBeacon],
        commands[PerformCommand.deactivateBeacon],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    options: {
      Default: [
        options[OptionName.noOption],
        options[OptionName.roe],
        options[OptionName.disperseOnAttack],
        options[OptionName.alarmState],
        options[OptionName.awarnessLevel],
        options[OptionName.engageAirWeapons],
        options[OptionName.aircraftInterceptRange],
        options[OptionName.altRestrictionMin],
        options[OptionName.altRestrictionMax],
        options[OptionName.restrictTarget],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
  },
  ship: {
    task: {
      Default: [
        performTask[Task.noTask],
        performTask[Task.fireAtPoint],
        performTask[Task.attackGroup],
        performTask[Task.goToWaypoint],
        performTask[Task.shipHoldPoint],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    enrouteTask: {
      Default: [enrouteTask[EnrouteTask.noEnrouteTask]],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    commands: {
      Default: [
        commands[PerformCommand.noAction],
        commands[PerformCommand.runScript],
        commands[PerformCommand.scriptFile],
        commands[PerformCommand.setInvisible],
        commands[PerformCommand.setImmortal],
        commands[PerformCommand.activateBeacon],
        commands[PerformCommand.deactivateBeacon],
        commands[PerformCommand.activateICLS],
        commands[PerformCommand.deactivateICLS],
        commands[Task.goToWaypoint],
        commands[PerformCommand.loadingShip],
        commands[PerformCommand.activateLink4],
        commands[PerformCommand.deactivateLink4],
        commands[PerformCommand.activateACLS],
        commands[PerformCommand.deactivateACLS],
        commands[Task.shipHoldPoint],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
    options: {
      Default: [
        options[OptionName.noOption],
        options[OptionName.roe],
        options[OptionName.alarmState],
        options[OptionName.awarnessLevel],
        options[OptionName.engageAirWeapons],
        options[OptionName.aircraftInterceptRange],
      ],
      AFAC: [],
      "Antiship Strike": [],
      CAS: [],
      Escort: [],
      "Ground Attack": [],
      Nothing: [],
      Reconnaissance: [],
      SEAD: [],
      Transport: [],
      AWACS: [],
      Airborne: [],
      CAP: [],
      "Fighter Sweep": [],
      GAI: [],
      Intercept: [],
      "Pinpoint Strike": [],
      Refueling: [],
      "Runway Attack": [],
    },
  },
};
