import { type SelectOption } from "naive-ui";
import type { TUpperLevelTasks, TGroupTypes } from "../types";

const weapons = {
  auto: {
    label: "Auto",
    value: 0,
  },
  nothing: {
    label: "No Weapon",
    value: 0,
  },
  all: {
    label: "All",
    value: 4294967295,
  },
  unguided: {
    label: "Unguided",
    value: 805339120,
  },
  cannon: {
    label: "Cannon",
    value: 805306368,
  },
  shells: {
    label: "Shells",
    value: 52344913920,
  },
  conventionalShell: {
    label: "Conventional Shell",
    value: 805306368,
  },
  markerShell: {
    label: "Marker Shell",
    value: 51539607552,
  },
  smokeShell: {
    label: "Smoke Shell",
    value: 17179869184,
  },
  candleShell: {
    label: "Candle Shell",
    value: 34359738368,
  },
  rockets: {
    label: "Rockets",
    value: 30720,
  },
  smokeRockets: {
    label: "Smoke Rockets",
    value: 4096,
  },
  lightRockets: {
    label: "Light Rockets",
    value: 2048,
  },
  candleRockets: {
    label: "Candle Rockets",
    value: 8192,
  },
  heavyRockets: {
    label: "Heavy Rockets",
    value: 16384,
  },
  bombs: {
    label: "Bombs",
    value: 2032,
  },
  ironBombs: {
    label: "Iron Bombs",
    value: 240,
  },
  clusterBombs: {
    label: "Cluster Bombs",
    value: 768,
  },
  candleBombs: {
    label: "Candle Bombs",
    value: 1024,
  },
  torpedoes: {
    label: "Torpedoes",
    value: 4294967296,
  },
  guided: {
    label: "Guided",
    value: 268402702,
  },
  guidedBombs: {
    label: "Guided Bombs",
    value: 14,
  },
  missiles: {
    label: "Missiles",
    value: 268402688,
  },
  ASM: {
    label: "ASM",
    value: 4161536,
  },
  ATGM: {
    label: "ATGM",
    value: 131072,
  },
  standardASM: {
    label: "Standard ASM",
    value: 1835008,
  },
  ARM: {
    label: "ARM",
    value: 32768,
  },
  antiship: {
    label: "Antiship",
    value: 65536,
  },
  cruiseMissile: {
    label: "Cruise Missile",
    value: 2097152,
  },
  AAM: {
    label: "AAM",
    value: 264241152,
  },
  SR_AAM: {
    label: "SR AAM",
    value: 4194304,
  },
  MR_AAM: {
    label: "MR AAM",
    value: 8388608,
  },
  LR_AAM: {
    label: "LR AAM",
    value: 16777216,
  },
  decoys: {
    label: "Decoys",
    value: 8589934592,
  },
};

const pgm = [
  weapons.guidedBombs,
  weapons.standardASM,
  weapons.ARM,
  weapons.antiship,
  weapons.cruiseMissile,
];

const marker = [
  weapons.unguided,
  weapons.cannon,
  weapons.rockets,
  weapons.lightRockets,
  weapons.heavyRockets,
  weapons.smokeRockets,
  weapons.candleRockets,
  weapons.candleBombs,
  weapons.bombs,
  weapons.ironBombs,
  weapons.clusterBombs,
  weapons.candleBombs,
  weapons.guided,
  weapons.guidedBombs,
  weapons.missiles,
  weapons.ASM,
  weapons.ATGM,
  weapons.standardASM,
  weapons.ARM,
  weapons.antiship,
  weapons.cruiseMissile,
  weapons.AAM,
  weapons.SR_AAM,
  weapons.MR_AAM,
  weapons.LR_AAM,
];

export const availableWeapons: Record<TGroupTypes, Record<TUpperLevelTasks, SelectOption[]>> = {
  nothing: {
    Default: [weapons.auto],
    AFAC: [],
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    "Pinpoint Strike": [],
    Refueling: [],
    "Runway Attack": [],
  },
  unknown: {
    Default: [
      weapons.unguided,
      weapons.cannon,
      weapons.rockets,
      weapons.lightRockets,
      weapons.heavyRockets,
      weapons.bombs,
      weapons.ironBombs,
      weapons.clusterBombs,
      weapons.candleBombs,
      weapons.torpedoes,
      weapons.guided,
      weapons.guidedBombs,
      weapons.missiles,
      weapons.ASM,
      weapons.ATGM,
      weapons.standardASM,
      weapons.ARM,
      weapons.antiship,
      weapons.cruiseMissile,
      weapons.AAM,
      weapons.SR_AAM,
      weapons.MR_AAM,
      weapons.LR_AAM,
      weapons.decoys,
    ],
    AFAC: [],
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    "Pinpoint Strike": [],
    Refueling: [],
    "Runway Attack": [],
  },
  plane: {
    Default: [
      weapons.cannon,
      weapons.AAM,
      weapons.SR_AAM,
      weapons.MR_AAM,
      weapons.LR_AAM,
      weapons.decoys,
    ],
    AFAC: [],
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    "Pinpoint Strike": [],
    Refueling: [],
    "Runway Attack": [],
  },
  helicopter: {
    Default: [weapons.cannon, weapons.AAM, weapons.SR_AAM, weapons.MR_AAM, weapons.LR_AAM],
    AFAC: [],
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    "Pinpoint Strike": [],
    Refueling: [],
    "Runway Attack": [],
  },
  vehicle: {
    Default: [
      weapons.unguided,
      weapons.cannon,
      weapons.rockets,
      weapons.lightRockets,
      weapons.heavyRockets,
      weapons.bombs,
      weapons.ironBombs,
      weapons.clusterBombs,
      weapons.candleBombs,
      weapons.guided,
      weapons.guidedBombs,
      weapons.ASM,
      weapons.ATGM,
      weapons.standardASM,
      weapons.ARM,
      weapons.decoys,
    ],
    AFAC: marker,
    "Pinpoint Strike": pgm,
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    Refueling: [],
    "Runway Attack": [],
  },
  ship: {
    Default: [
      weapons.unguided,
      weapons.cannon,
      weapons.rockets,
      weapons.lightRockets,
      weapons.heavyRockets,
      weapons.bombs,
      weapons.ironBombs,
      weapons.clusterBombs,
      weapons.candleBombs,
      weapons.torpedoes,
      weapons.guided,
      weapons.guidedBombs,
      weapons.ASM,
      weapons.ATGM,
      weapons.standardASM,
      weapons.ARM,
      weapons.antiship,
      weapons.decoys,
    ],
    AFAC: marker,
    "Pinpoint Strike": pgm,
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    Refueling: [],
    "Runway Attack": [],
  },
  static: {
    Default: [
      weapons.unguided,
      weapons.cannon,
      weapons.rockets,
      weapons.lightRockets,
      weapons.heavyRockets,
      weapons.bombs,
      weapons.ironBombs,
      weapons.clusterBombs,
      weapons.candleBombs,
      weapons.guided,
      weapons.guidedBombs,
      weapons.ASM,
      weapons.ATGM,
      weapons.standardASM,
      weapons.cruiseMissile,

      weapons.decoys,
    ],

    AFAC: marker,
    "Pinpoint Strike": pgm,
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    Refueling: [],
    "Runway Attack": [],
  },
  point: {
    Default: [
      weapons.unguided,
      weapons.cannon,
      weapons.rockets,
      weapons.lightRockets,
      weapons.heavyRockets,
      weapons.bombs,
      weapons.ironBombs,
      weapons.clusterBombs,
      weapons.candleBombs,
      weapons.guided,
      weapons.guidedBombs,
      weapons.ASM,
      weapons.ATGM,
      weapons.standardASM,
      weapons.cruiseMissile,

      weapons.decoys,
    ],
    AFAC: marker,
    "Pinpoint Strike": pgm,
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    Refueling: [],
    "Runway Attack": [],
  },
  runway: {
    Default: [
      weapons.unguided,
      weapons.heavyRockets,

      weapons.bombs,
      weapons.ironBombs,
      weapons.clusterBombs,
      weapons.candleBombs,

      weapons.guided,
      weapons.guidedBombs,
      weapons.ASM,
      weapons.standardASM,
      weapons.cruiseMissile,
    ],
    "Pinpoint Strike": pgm,
    AFAC: [],
    "Antiship Strike": [],
    CAS: [],
    Escort: [],
    "Ground Attack": [],
    Nothing: [],
    Reconnaissance: [],
    SEAD: [],
    Transport: [],
    AWACS: [],
    Airborne: [],
    CAP: [],
    "Fighter Sweep": [],
    GAI: [],
    Intercept: [],
    Refueling: [],
    "Runway Attack": [],
  },
};
